export const ProjectFilterList = [
  {
    label: "Show All",
    value: "",
  },
  {
    label: "Show Favorite",
    value: "",
  },
  {
    label: "Show On Hold",
    value: "",
  },
  {
    label: "Show Open",
    value: "",
  },
  {
    label: "Show Closed",
    value: "",
  },
  {
    label: "Show Invoiced",
    value: "",
  },
];

export const ProjectCardListSelect = [
  "Add",
  "New",
  "Percent",
  "Update",
  "Stage",
  "Conclude",
];

export const ProjectData = [
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "TEST",
    projectCode: "Pro-1",
    manager: "First Name",
    Admin: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
];
